name: Docker Build

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  docker:
    name: Docker
    uses: ./.github/workflows/_docker-ci.yml
    with:
      REGISTRY: "ghcr.io"
      IMAGE_NAME: "${{ github.repository }}-cli"
      TEST_CN: "*.<domain>"
    secrets: inherit
